SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- TABEL PRODUS_COMANDA

CREATE TABLE IF NOT EXISTS `produs_comanda` (
  `id_comanda` int(11) NOT NULL,
  `id_produs` int(11) NOT NULL,
  `nr_produse` int(11) NOT NULL,
  PRIMARY KEY (`id_comanda`,`id_produs`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;



-- DATE TABEL PRODUS COMANDA

INSERT INTO `produs_comanda` (`id_comanda`, `id_produs`, `nr_produse`) VALUES
(1, 1, 3),
(1, 10, 2),
(2, 5, 1),
(2, 2, 2),
(3, 5, 1);



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;


