
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


-- TABEL COMANDA

CREATE TABLE IF NOT EXISTS `comanda` (
  `id_comanda` int(11) NOT NULL AUTO_INCREMENT,
  `id_utilizator` int(11) NOT NULL,
  `valoare` decimal(6,2) NOT NULL,
  `data` datetime NOT NULL,
  `onorare` binary(1) NOT NULL,
  PRIMARY KEY (`id_comanda`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;



-- DATE TABEL COMANDA

INSERT INTO `comanda` (`id_comanda`, `id_utilizator`, `valoare`, `data`, `onorare`) VALUES
(1, 2, 44.00, '2017-01-10 01:39:03', '1'),
(2, 2, 86.20, '2017-03-21 01:52:01', '0');






/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

